admiraltyio/admiralty

cmd/agent/main.go
=> Namespaced shared informer factory for feedback controller to watch remote pod chaperons

pkg/scheduler_plugins/proxy/plugin.go
fix #20
The proxy pod scheduler's filter plugin creates candidate pods in target clusters and waits for those pods to be reserved or unschedulable, and filters the corresponding virtual nodes accordingly. If it is not allowed to create a candidate in a target cluster, it knows to filter out the corresponding virtual node. But if it receives any other error, including if the namespace doesn't exist, the entire scheduling cycle fails, when only that virtual node should be filtered out.
=> handle pod chaperon get/create errors as unschedulable

README.md, charts/multicluster-scheduler/README.md
=> document k8s version requirement

charts/multicluster-scheduler/README.md, charts/multicluster-scheduler/templates/deploy.yaml, charts/multicluster-scheduler/values.yaml, test/e2e/argo-workflow/values-cluster1.yaml, test/e2e/argo-workflow/values-cluster2.yaml
=> fix #25: reorg Helm values

pkg/model/delegatepod/model.go
=> fix #26: remove init container service account volume mount

pkg/model/delegatepod/model.go
=> fix #26: actually remove init container service account volume mount

.github/workflows/go.yml, pkg/controllers/follow/cm.go, pkg/controllers/follow/secret.go, test/e2e/e2e.sh
=> finalizers added to multi-cluster config maps and secrets only

pkg/vk/node/node.go, pkg/webhooks/proxypod/proxypod.go, pkg/webhooks/proxypod/proxypod_test.go
=> tolerate network unavailable

proposals/decentralized.md
=> Proposal: Fully Decentralized Multi-Cluster Scheduler

cmd/agent/main.go, pkg/config/agent/agent.go, pkg/controllers/resources/upstream.go, pkg/controllers/source/controller.go, pkg/model/proxypod/model.go, pkg/name/name.go, pkg/name/name_test.go, pkg/scheduler_plugins/proxy/plugin.go
=> Fix name collisions and truncate names

pkg/controller/controller.go, pkg/controllers/follow/cm.go, pkg/controllers/follow/secret.go, pkg/model/delegatepod/model.go
because label values can't fit parent names longer than 63 chars
fix #54
=> use annotations for remote controller ref

charts/multicluster-scheduler/templates/cr.yaml, charts/multicluster-scheduler/templates/deploy.yaml, cmd/agent/main.go, go.sum, pkg/vk/csr/csr.go, pkg/vk/http/http.go, pkg/vk/http/opts.go, pkg/vk/http/provider.go, pkg/vk/node/node.go, test/e2e/argo.sh, test/e2e/e2e.sh, test/e2e/exec/test.sh, test/e2e/exec/test.yaml, test/e2e/logs/test.sh, test/e2e/logs/test.yaml, third_party/github.com/jetstack/cert-manager/pkg/util/pki/keyusage.go
csr signed by kube-apiserver
fix #35 
=> vk logs and exec provider

pkg/model/proxypod/model.go, pkg/scheduler_plugins/candidate/plugin.go, pkg/scheduler_plugins/proxy/plugin.go
=> don't crash if pod annotated in unlabeled namespace

cmd/restarter/main.go, pkg/config/agent/agent.go, pkg/controllers/target/controller.go, test/e2e/exec/test.sh, test/e2e/topologies/namespaced-burst/cluster1/targets.yaml
=> Skip invalid targets instead of crashing, and reload on kubeconfig secret changes

charts/multicluster-scheduler/templates/cr.yaml, cmd/agent/main.go, pkg/controllers/resources/downstream.go, pkg/controllers/resources/upstream.go, pkg/vk/node/provider.go, pkg/vk/node/run.go
=> Fix multiple huge page sizes support skew

cmd/remove-finalizers/main.go
=> fix post delete helm hook patch

charts/multicluster-scheduler/templates/cr.yaml, cmd/agent/main.go, cmd/remove-finalizers/main.go, pkg/controllers/follow/ingress/controller.go, test/e2e/e2e.sh, test/e2e/ingress/test.sh, test/e2e/ingress/test.yaml
=> ingresses follow

pkg/controllers/follow/service/controller.go
=> save original selector

charts/multicluster-scheduler/templates/cr.yaml, pkg/common/constants.go, pkg/controllers/resources/downstream.go, pkg/controllers/resources/upstream.go, pkg/model/delegatepod/model.go, pkg/model/virtualnode/model.go, pkg/vk/node/node.go, pkg/webhooks/proxypod/proxypod.go, pkg/webhooks/proxypod/proxypod_test.go, test/e2e/e2e.sh
=> cluster-level scheduling constraints

build/build_one.sh, release/chart.sh, release/image.sh, release/images.sh
=> upx for amd64 only

go.mod, pkg/controllers/follow/ingress/controller.go, pkg/controllers/follow/ingress/controller_test.go, test/e2e/ingress/test.sh
* shouldUpdate function which detects the need
of remoteIngress update and also mutates Spec and
annotation of associated remoteIngressCopy
* Update remoteIngress according to result of
shouldUpdate function
* Unit tests
* Annotation e2e test
=> Update remote Ingress on annotation change

charts/multicluster-scheduler/templates/cr.yaml, pkg/common/constants.go, pkg/controllers/cleanup/controller.go, test/e2e/cleanup/test.sh, test/e2e/cleanup/test.yaml, test/e2e/e2e.sh
#135 was merged too soon
this PR fixes it and includes a test
=> fix cleanup

pkg/controllers/follow/service/controller.go, test/e2e/argo.sh, test/e2e/cleanup/test.sh, test/e2e/delete-delegate/test.sh, test/e2e/ingress/test.sh, test/e2e/no-reservation/test.sh, test/e2e/no-rogue-finalizer/test.sh
handle new ClusterIPs dual-stack field
=> fix service propagation

pkg/generated/clientset/versioned/fake/register.go, pkg/generated/clientset/versioned/scheme/register.go, pkg/model/delegatepod/model.go, test/e2e/e2e.sh, test/e2e/priorityclass.yaml
=> Different default priority

.github/workflows/go.yml, pkg/controllers/feedback/controller.go, pkg/controllers/follow/cm.go, pkg/controllers/follow/secret.go, test/e2e/cleanup/test.sh, test/e2e/delete-chaperon/test.sh, test/e2e/delete-chaperon/test.yaml, test/e2e/delete-delegate/test.sh, test/e2e/e2e.sh, test/e2e/no-reservation/test.sh
fixes #151 
also actually call e2e test for delegate recreation #145
=> delete proxy pod when chaperon deleted

pkg/webhooks/proxypod/proxypod.go
=> fix use-constraints-from-spec-for-proxy-pod-scheduling when webhook is reinvocated
