charts/multicluster-scheduler/templates/cr.yaml
charts/multicluster-scheduler/templates/post-delete/cr.yaml
cmd/agent/main.go
cmd/remove-finalizers/main.go
pkg/controllers/chaperon/controller.go
pkg/controllers/feedback/controller.go
pkg/controllers/follow/cm.go
pkg/controllers/follow/secret.go
test/e2e/argo.sh
test/e2e/e2e.sh
test/e2e/follow/test.sh
test/e2e/follow/test.yaml

If a proxy pod refers to config maps or secrets to be mounted as volumes, projected volumes, used as environment variables or, for secrets, as image pull secrets, Admiralty copies those config maps or secrets to the target cluster where the corresponding delegate pod runs.
fix #32

config maps and secrets follow pods

---

charts/multicluster-scheduler/templates/deploy.yaml
pkg/controllers/source/controller.go

hardcoded values only worked if release was named "multicluster-scheduler"
fix #55

get source cluster role names from env passed by chart

---

pkg/controller/controller.go
pkg/controllers/source/controller.go
pkg/controllers/target/controller.go

the "successfully synced" message is especially confusing if nothing is synced, because, e.g., the key is filtered out when it's handled, rather than upstream in event handlers

remove unnecessary (sometimes confusing) logs

---

.github/workflows/go.yml
build/Dockerfile
build/build_one.sh
build/install_docker.sh
pipeline.sh
release/chart.sh
release/image.sh
release/images.sh
test/e2e/admiralty.sh
test/e2e/e2e.sh

- refactor single build/release into separate scripts
- build for multiple architectures (except in dev/CI) and push multi-arch manifests (amd64, arm64, ppc64le, and s390x, per requests from users, fix #27)
- compress binaries with UPX (except for s390x which isn't supported by UPX)
- build debug images (TODO: wire up in Helm chart)

changes to build/release scripts

---

pkg/common/constants.go
pkg/model/delegatepod/model.go
pkg/scheduler_plugins/proxy/plugin.go

filter virtual nodes over multiple scheduling cycles
fix #82 

no-reservation annotation to work without candidate scheduler

---

.github/workflows/go.yml
build/build_one.sh
build/load.sh
charts/multicluster-scheduler/templates/deploy.yaml
test/e2e/kind.sh

Split the current single multi-step GitHub Actions job into two, so a matrix of e2e test jobs can run in parallel after the build job runs once.
Pick kind node image based on K8S_VERSION environment variable.

e2e test for k8s versions 1.17 through 1.22

---

.github/workflows/go.yml

Although we use continue-on-error (GitHub Actions job setting) for 1.22, and the workflow does succeed even if the job fails, PR and commit checks appear failing, which isn't our intention:
- https://github.community/t/continue-on-error-allow-failure-ui-indication/16773/14
- https://github.com/actions/toolkit/issues/399

disable e2e test for k8s 1.22 for now

---

charts/multicluster-scheduler/templates/cm.yaml
charts/multicluster-scheduler/templates/deploy.yaml
charts/multicluster-scheduler/values.yaml

- so users starting with 1 replica per deployment can scale them out directly rather than via helm
- use 2 replicas by default so PDB isn't an issue
- (unrelated) use system-cluster-critical priority class to limit preemption and guarantee scheduling

Always enable leader election

---

cmd/agent/main.go
pkg/apis/multicluster/v1alpha1/clustertarget_types.go
pkg/apis/multicluster/v1alpha1/target_types.go
pkg/apis/multicluster/v1alpha1/zz_generated.deepcopy.go
pkg/config/agent/agent.go
pkg/controllers/resources/upstream.go
pkg/controllers/resources/upstream_test.go
test/e2e/e2e.sh
test/e2e/virtual-node-labels/test.sh

via regexp configured on targets, matching labels formatted as key=value
see unit tests for examples
TODO: proper user documentation
fixes #114 with the following (Cluster)Target patch:
```yaml
spec:
excludedLabelsRegexp: ^kubernetes\.azure\.com/cluster=
```

exclude labels from aggregation on virtual nodes

---

cmd/agent/main.go
cmd/remove-finalizers/main.go
pkg/controller/controller.go
pkg/controllers/feedback/controller.go
pkg/controllers/follow/cm.go
pkg/controllers/follow/ingress/controller.go
pkg/controllers/follow/secret.go
pkg/controllers/follow/service/controller.go
pkg/controllers/resources/upstream.go
pkg/controllers/resources/upstream_test.go
pkg/webhooks/proxypod/proxypod.go
pkg/webhooks/proxypod/proxypod_test.go

The problem with fan-out controllers was that they wouldn't start if one target was unavailable (blocked at WaitForCacheSync, and we'd rather sync the cache before reconciling).
Another benefit is the use of more namespaced informers (safer, faster).
Note: this reopens a rare race condition where candidates can be orphaned if proxy pods are deleted before finalizers are added (they can't be added before because that would invalidate the proxy scheduler cache mid-cycle). This is a trade-off. We will eventually need proper GC and let go of finalizers and their many flaws.
fixes #106

refactor controllers from fan-out to 1-on-1

---

cmd/agent/main.go
pkg/vk/csr/csr.go

start VK server asynchronously
otherwise, startup hangs before controllers run if CSR is never signed (e.g., on EKS 1.19+, because we use the v1beta1 API, cf. #120)
also timeout waiting for CSR to be signed, so we can log that remote logs and exec won't work

disable logs/exec if CSR is not signed after 30s

---

charts/multicluster-scheduler/templates/quota.yaml

priority class which is used by Admiralty pods
because GKE (and possibly other distributions) limits this priority class's consumption by default using https://kubernetes.io/docs/concepts/policy/resource-quotas/#limit-priority-class-consumption-by-default
fixes #124

add resource quota in release namespace for system-cluster-critical

---

charts/multicluster-scheduler/templates/deploy.yaml

policy/v1 was introduced in 1.21, which is our minimum requirement now
policy/v1beta1 will be dropped in 1.25, so upgrading ensures we'll support 1.25 (unless something else breaks)

upgrade PodDisruptionBudgets to policy/v1

---

.gitignore
pkg/scheduler_plugins/candidate/plugin.go
test/e2e/delete-delegate/test.sh
test/e2e/delete-delegate/test.yaml

do not reset podchaperon is-allowed annotation, because proxy pod doesn't go through scheduling again, so cannot set it
note (to be implemented later): we should only recreate if connection is lost, and preferably delete the proxy pod, to potentially schedule replacement in a different target

fix recreate delegate pod when deleted

---

pkg/model/virtualnode/model.go

This change adds the label adopted in Kubernetes 1.16 and keeps the legacy label that was deprecated.
Signed-off-by: Byran Carlock <bcarlock@emergemarket.com>

patch for #156 https://github.com/admiraltyio/admiralty/issues/156

---

charts/multicluster-scheduler/templates/deploy.yaml
charts/multicluster-scheduler/values.yaml
cmd/agent/main.go
pkg/common/constants.go
pkg/controller/controller.go
pkg/controllers/feedback/controller.go
pkg/controllers/follow/cm.go
pkg/controllers/follow/ingress/controller.go
pkg/controllers/follow/secret.go
pkg/controllers/follow/service/controller.go
pkg/model/delegatepod/model.go
pkg/scheduler_plugins/proxy/plugin.go

Cross-cluster GC after delete

---

cmd/agent/main.go

https://github.com/admiraltyio/admiralty/blob/1c8f37843e3bf1505de1a68ee518739c1c49d956/cmd/agent/main.go#L328

change wait.ErrWaitTimeout method to wait.Interrupted() as wait.ErrWaitTimeout was deprecated

---

charts/multicluster-scheduler/README.md
charts/multicluster-scheduler/templates/webhook.yaml
charts/multicluster-scheduler/values.yaml

This Pull Requests adds possibility to customize reinvocationPolicy for webhook deployed by HELM chart.
This closes #192 and allows to use admirality in conjunction with other webhooks 
In order to provide backward compatibility - default value is set to `Never` (as it is default for kubernetes)
Docs: https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#reinvocation-policy

add support for reinvocationPolicy

---

pkg/controllers/feedback/controller.go
pkg/controllers/feedback/controller_test.go

If extra containers are injected, the status for those containers is getting reported back into the proxy pod status.
This confuses or breaks clients reading pod status expecting every named container status to correlate to a named container in pod spec (for example, https://github.com/kubernetes/kubernetes/pull/124906).
This PR prunes out container statuses for named containers which do not exist in the proxy pod.

Filter pod statuses reported back to containers which exist in proxy pod

---

charts/multicluster-scheduler/templates/cm.yaml

This came up while testing a setup with a target cluster that autoscales a GPU pool from zero and a pod requesting GPU resources. The pod remains pending with:
```
Warning  FailedScheduling   3m52s       admiralty-proxy     0/5 nodes are available: 1 Insufficient nvidia.com/gpu
```
This is because the virtual node representing the target cluster doesn't have the GPU capacity populated (it can't fetch it anyways because the target cluster has 0 nodes). The expectation is that the proxy-scheduler would still create the pod chaperon, autoscaler kicks in and the rest of the binding process happens but that wasn't the case.
On investigation, it seems that the `Filter` extension point in the proxy scheduler never gets to execute. The reason is because the scheduler configuration is using a …

fix: support scale from zero in the proxy scheduler

---

pkg/scheduler_plugins/proxy/plugin.go
pkg/scheduler_plugins/proxy/utils.go
pkg/scheduler_plugins/proxy/utils_test.go

We use admiralty alongside Kueue for scheduling plain pod workloads on the target clusters. For plain pod management, Kueue utilizes [scheduling gates](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-scheduling-readiness/) to block the scheduling cycle from running. The scheduling gate remains on the pod until Kueue admits the pod when quota is available. Pods that are scheduling gated don't have the `PodReasonUnschedulable` as the condition reason and therefore, may cause unnecessary delays in the filter step since it polls for the entirety of the 30 seconds waiting for `PodReasonUnschedulable`.
This fixes this logic to consider pods with scheduling gates as unschedulable.

fix(proxy scheduler): exit filter step early when scheduling gates are found

---

docs/user_guide/pod_configuration.md
pkg/common/constants.go
pkg/controllers/follow/service/controller.go
pkg/model/delegatepod/model.go
pkg/model/delegatepod/model_test.go

This allows specifying an annotation in a similar fashion to `use-constraints-from-spec-for-proxy-pod-scheduling` that would allow labels to be copied as is from the proxy pod to the delegate pod without replacing the label key domain with `multicluster.admiralty.io/`. 
The motivation behind this is to enable a multicluster Kueue setup through admiralty. In that setup, admission is gated by ClusterQueues in target clusters. Kueue only operates on pods labeled with `kueue.x-k8s.io/queue-name` and having admiralty prefix this with `multicluster.admiralty.io/` would break this interaction.

feat: allow labels to be copied to delegate pods without prefix
